secrets:
  juicefs_encryption_key:
    file: ./secrets/juicefs-priv-key.pem

services:
  juicefs-format:
    image: juicedata/mount
    command: >
      juicefs format
      --storage s3
      --bucket https://minio
      --access-key=${MINIO_ADMIN_USERNAME}
      --secret-key=${MINIO_ADMIN_PASSPHRASE}
      rediss://${REDIS_USERNAME}:${REDIS_PASSPHRASE}@redis:6379/1
      backupvol
    depends_on:
      - minio
      - redis


  juicefs-mount:
      image: juicedata/mount
      container_name: backupvol
      depends_on:
        - juicefs-format
      volumes:
        - ./mnt:/mnt:rw,rshared
      cap_add:
        - SYS_ADMIN
      devices:
        - /dev/fuse
      security_opt: 
        - apparmor:unconfined
      command: ["juicefs", "mount", "rediss://${REDIS_USERNAME}:${REDIS_PASSPHRASE}@redis:6379/1", "/mnt"]
      restart: unless-stopped


  minio:
    container_name: minio
    image: minio/minio:latest
    # ports:
    #   - "9000:9000"
    #   - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ADMIN_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_ADMIN_PASSPHRASE}
    restart: always
    volumes:
      - /tmp/minio/data:/data
    command: server /data --console-address ":9001"


  createbuckets:
    image: quay.io/minio/mc:RELEASE.2025-03-12T17-29-24Z
    depends_on:
      - minio
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set dockerminio http://minio:9000 ${MINIO_ADMIN_USERNAME} ${MINIO_ADMIN_PASSPHRASE};
      /usr/bin/mc mb dockerminio/megas4/subdir;
      exit 0;
      "

  redis:
    container_name: redis
    image: redis
    restart: always
    # ports:
    #   - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSPHRASE}
    volumes: 
      - /tmp/redis/data:/data

volumes:
  redisvol:
    driver: local